### ISSUE TITLE
Remote command bus

### ISSUE THREAD

**Issue by sagikazarmark** [rosstuck/tactician#1]
I started to work on a remote command bus which sends the command to a remote location (using Bernardphp for message queue abstraction) for processing there by a local command bus implementation. Are you interested in it?

It integrates into the command bus pattern, so a developer is able to dynamically decide whether he/she wants to handle the command in the foreground or in the background.

**Comment by sagikazarmark** [comment]
For the record: https://github.com/indigophp/doris

We will discuss things later

**Comment by rosstuck** [comment]
For future reference, this spawned Doris. https://github.com/indigophp/doris

@sagikazarmark Going to close this issue for now and then reopen once we get the repos transferred over to the League. :smile:

**Comment by acairns** [comment]
Also waiting for the league package before I fork - finally had our spike today regarding our queue system.

**Comment by sagikazarmark** [comment]
@rosstuck Close it at will.
